### ISSUE TITLE
make modern fails due to return mismatch

### ISSUE THREAD

**Issue by guilgien** [cRz-Shadows/Pokemon_Emerald_Legacy#2]
`make modern` fails with the following error:
```
/opt/devkitpro/devkitARM/bin/../libexec/gcc/arm-none-eabi/14.2.0/cc1 -quiet <flags> -o build/modern/src/field_specials.o src/field_specials.c
src/field_specials.c: In function 'TryChangeDeoxysForm':
src/field_specials.c:4370:10: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
 4370 |          return;
      |          ^~~~~~
src/field_specials.c:4346:8: note: declared here
 4346 | bool16 TryChangeDeoxysForm(void)
      |        ^~~~~~~~~~~~~~~~~~~
src/field_specials.c:4375:5: error: 'return' with no value, in function returning non-void -Wreturn-mismatch]
 4375 |     return;
      |     ^~~~~~
src/field_specials.c:4346:8: note: declared here
 4346 | bool16 TryChangeDeoxysForm(void)
      |        ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:335: build/modern/src/field_specials.o] Error 1
make: *** Deleting file 'build/modern/src/field_specials.o'
```

[The base disassembly](https://github.com/pret/pokeemerald) builds without issue using `make modern` on my machine, so this does seem to be an issue with this project's additions.

**Comment by cromerc** [comment]
I opened I pull request which I believe should fix this issue.

**Comment by cRz-Shadows** [comment]
I've changed the function to a void, since the return values wouldn't do anything anyway. Let me know if that fixes it.

**Comment by guilgien** [comment]
yeah, `make modern` now completes without any error

**Comment by ShadowzLmao2** [comment]
> yeah, `make modern` now completes without any error

Wouldn't it be better to run "make -j#" instead of "make modern"?

**Comment by cromerc** [comment]
> > yeah, `make modern` now completes without any error
> 
> Wouldn't it be better to run "make -j#" instead of "make modern"?

You misunderstood what modern does, it uses a modern toolset to compile the game. You can add -j# to both of those commands, but it doesn't change which toolset is used:
"make -j8" builds it with 8 cores using the old toolset.
"make -j8 modern" builds it with 8 cores using the modern toolset.
