### ISSUE TITLE
Rare Candies, Master Balls, and other suggestions

### ISSUE THREAD

**Issue by ShadowzLmao2** [cRz-Shadows/Pokemon_Emerald_Legacy#4]
Is it possible to have an NPC give the player 1000 rare candies and MAYBE master balls? It could be when the player obtains pokeballs from the professor in the short tutorial. I would recommend only putting this in the hardcore mode, but they can be given in any mode. If you want me to send code for it, lmk because I can easily make the changes for you and just send the code. Feel free to close this issue if adding rare candies is not in scope of the project, after all i could always clone the repo myself and change it on my branch for myself.
Is it also possible to change the intro speech? that way the project can have personality and give information that the team feels the player should know.
Can we also link the documentation in the README here?
BUG: Rare candies allow you to revive a pokemon, but healing it with nurse joy does not restore hp/pp/status
Documentation BUG: Maxie Mt Chimney is not documented

**Comment by cRz-Shadows** [comment]
Absolutely not
