### ISSUE TITLE
Triple Power Still may not be scaled.

### ISSUE THREAD

**Issue by Bruhcation** [cRz-Shadows/Pokemon_Emerald_Legacy#6]
![Screenshot 2024-12-29 130703](https://github.com/user-attachments/assets/459ccdce-b840-43a9-bd59-4539ee00db79)

While doing my firered romhack I noticed when I set triple Kick to 30 it doesn't actually have 30 power and do less damage. And from what I've seen in data/battlescripts triple kick has this part were next to it, it was set to zero. When I set it to 20 it actually did a lot more damage. I think the code works where the power starts at 0+10 first turn, 10+10 second turn, 20+10 last turn

**Comment by cRz-Shadows** [comment]
Thanks for the heads up, we didn't even change triple kick since its literally only on hitmontop that's only available in the post game, but looking at it now I've changed it to match CL by changing `addbyte sTRIPLE_KICK_POWER, 10` to 20
